version: '2'
services:
    db:
        build: ./database
        restart: always
        ports: 
            - "${MYSQL_PORT}:3306"
        networks:
            - default
        env_file:
            - .env
    pinder_server:
        build:
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - ./server:/usr/src/app/server
            - /usr/src/app/server/node_modules
        ports:
            - "3000:3000"
        links:
            - db:db
        env_file: 
            - .env
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8081:80
        env_file:
            - .env
        depends_on:
            - db
    