FROM node:10-alpine
EXPOSE 3000
RUN mkdir -p /usr/src/app/server
WORKDIR /usr/src/app/server
COPY . /usr/src/app/server
RUN npm install -g nodemon
RUN npm install
ENTRYPOINT ["nodemon","--legacy-watch", "/usr/src/app/server/index.js"]